server:
    port: 8761
spring:
    application:
        name: eureka-server
eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF
    pattern:
        console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'