server:
    port: 8080
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            routes:
                - id: authorization
                  uri: lb://django-authorization
                  predicates:
                      - Path=authorization/**
                  filters:
                      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                      - RewritePath=/authorization/(?<segment>.*),/authorization/$\{segment}
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/